// Generated by LiveScript 1.2.0
(function(){
  var _, moment, fs, color, ref$, spawn, kill, __q, sh, os, shelljs, ut, winston, path, dispOk, dispKo, disp, pdisp, pdeb, _module;
  _ = require('underscore');
  _.str = require('underscore.string');
  moment = require('moment');
  fs = require('fs');
  color = require('ansi-color').set;
  ref$ = require('child_process'), spawn = ref$.spawn, kill = ref$.kill;
  __q = require('q');
  sh = require('shelljs');
  os = require('os');
  shelljs = sh;
  ut = require('utf-8');
  winston = require('winston');
  path = require('path');
  dispOk = function(){
    return winston.info("Ok");
  };
  dispKo = function(it){
    return winston.error(it.toString());
  };
  disp = winston.info;
  pdisp = console.log;
  pdeb = winston.warn;
  _.mixin(_.str.exports());
  _.str.include('Underscore.string', 'string');
  _module = function(){
    var getBaseConfigPath, innerModule, iface;
    getBaseConfigPath = function(){
      var doesExist, res;
      doesExist = function(f){
        var x;
        x = shelljs.test('-e', path.resolve(f));
        return x;
      };
      res = (function(){
        switch (false) {
        case !doesExist('./.sk-files/config.js'):
          return path.resolve('./.sk-files/config.js');
        case !doesExist('./config.js'):
          return path.resolve('./config.js');
        case !doesExist(process.env.HOME + '/.sk-files/config.js'):
          return process.env.HOME + '/.sk-files/config.js';
        default:
          return null;
        }
      }());
      return res;
    };
    innerModule = function(){
      return root;
    };
    iface = {
      innerModule: innerModule,
      getBaseConfigPath: getBaseConfigPath
    };
    return iface;
  };
  module.exports = _module();
}).call(this);
